spring:
  datasource:
    url: jdbc:mysql://<Thay bằng DB host>/techmaster?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
auth:
  jwt:
    secret: alkfhdskfdksahfkjdshakflhasdjklfhkjdsahfkhdskfhsdla
payment:
  vn-pay:
    code: <Thay bằng VNPAY tmn code>
    secret: <Thay bằng VNPAY secret key>
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    query-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    callback: http://localhost/api/vn-pay/callback
